import React from 'react'
import arrowUp from '../assets/arrow-up.jpg';
import pencil from '../assets/pencil.png'
import question from '../assets/question.png'
import plus from '../assets/Plus-Math.png'
import { Link } from 'react-router-dom'
// import '../sass/password.scss'

function Password() {
  return (
    <>
     <span
      ><strong
        ><h2 className="" style={{padding: "2rem 0 0 2rem"}}>Settings</h2></strong></span>
    <span
      className="arrow d-flex"
      style={{justifyContent: "space-between", width: "40%"}}
    >
      <img src={arrowUp} alt="" width="20px" height="20px" />
      <h5>Password and Security</h5>
    </span>

    <section className="preview_section_div password">
      <div className="prev" style={{padding: "0 0 0 2rem"}}>
        <button className="mt-4" style={{width: "200px"}}>Password and Security</button>
        <Link to={'/billing'} style={{textDecoration: 'none', color: 'black'}}> 
          <h6>Billing and Payment</h6>
          </Link>
          <Link to={'/settings'} style={{textDecoration: 'none', color: 'black'}}> 
          <h6>Notifications</h6>
          </Link>
        
      </div>

      <div className="">
        <h4><strong>Authentication Options</strong></h4>

        <div className="password_div">
          <span>
            <h6>Password has been set</h6>
            <p>
              Choose a strong, unique password that is at least 8 characters
              long.
            </p>
          </span>
          <div className="edit">
            <img src={pencil} alt="#" /><button>Edit</button>
          </div>
        </div>
        <hr />
        <div className="password_div">
          <span
            ><h4>Two Step Verification Options</h4>
            <p>
              Add an extra layer of security to block unauthorized access and
              protect your account.
            </p>
          </span>
          <img src={question} alt="" width="30px" height="35px"/>
        </div> <hr/>
        <div className="password_div">
          <span><h6>Authentication App Code (Recommended)</h6>
            <p>
              Enter a code generated by your authenticator app to confirm its you.
            </p></span>
            <input type="range" />
        </div><hr/>
         <button class="edits">Save</button>
      </div>
    </section>
    </>
  )
}

export default Password